### PR TITLE
On recent nix versions, we need to have the flakes experimental feature enabled.

### PR DESCRIPTION
**Pull request by R-VdP**

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]

**Comment by R-VdP** [comment]
@rgri any change of getting a merge on this one?

**Comment by rgri** [comment]
Hi @R-VdP ! Sorry for the radio silence. Yeah, I added something similar to this on the [recursion](https://github.com/rgri/tex2nix/tree/recursion) branch, but I can merge this PR too. 

On newer versions of nix, the binary doesn't work without your change, right?

**Comment by rgri** [comment]
Also, please change the name of your commit to be more concise.

**Comment by Mic92** [comment]
What are the projects conventions?

**Comment by rgri** [comment]
I was just thinking it might be nice to have a shorter phrase. It's not that big of a deal. Will merge!

**Pull request merged**
